### ISSUE TITLE
Text duplication and truncation in email with attachment

### ISSUE THREAD

**Issue by jmac-atgit** [apparition47/MailTrackerBlockerApp#10]
I've twice seen a problematic display of emails (from the same sender) when the MTB extension is enabled and the email has an included attachment.

See the attached screenshots. When MTB is enabled, the message text "above" the placement of the inline attachment is duplicated "after" the attachment, whereas message text "after" the attachment is not displayed at all.

(I will privately send the message source to apparition47.)

macOS 14.4.1 and macOS 14.5
MTB 1.0.8
(I also have the GPG Mail 8.0 extension installed. The issue I reported still occurs whether the GPG Mail extension is 
enabled or disabled.)

=====

Display with MTB enabled:

![Email - MTB enabled](https://github.com/apparition47/MailTrackerBlockerApp/assets/80604317/54594603-50d2-4f53-abd5-6cfc9e2383ed)

Display with MTB disabled:

![Email - MTB disabled](https://github.com/apparition47/MailTrackerBlockerApp/assets/80604317/6f87aaf2-4386-4ac6-9de3-2020b825656a)

**Comment by apparition47** [comment]
>MTB 1.0.8

Do you still have this issue on the latest 1.0.10?

**Comment by jmac-atgit** [comment]
Sorry, I wasn't aware of the update. I did just now install it and still see the same issue.

**Comment by apparition47** [comment]
Fixed in 1.0.11. Should be available tomorrow.

MTB wasn't handling multipart emls with more than one HTML inside.

Thanks again for your support!
