### ISSUE TITLE
Empty emails

### ISSUE THREAD

**Issue by plsvn** [apparition47/MailTrackerBlockerApp#12]
**Describe the bug**
email content does not load (email are totally empty)
"only" happens with, e.g., mails from BandCamp, Visa, a local forum...

disabling MTB extension fixes the issue

**Environment (please complete the following information):**
 - OS: macOS 14.5
 - MailTrackerBlocker version: 1.1.0

**Comment by apparition47** [comment]
Ah sorry, I see the issue. This will be fixed in 1.1.1 tomorrow.

**Comment by apparition47** [comment]
1.1.1 released.

If you still see "this message has no content" on the 2-line email preview on the left side, you may need to [rebuild your index](https://c-command.com/spamsieve/help/resetting-mail-s-privat) (this doesn't delete your emails--it just forces Mail to remake its index).

**Comment by plsvn** [comment]
thanks Aaron but... looks the issue is still there with emails as the one... I can't attach here 🙄

**Comment by apparition47** [comment]
My email is in my profile @apparition47 . Please save the EML then send it to me if possible.

**Comment by apparition47** [comment]
This is what I'm seeing on 1.1.1 with `Welcome to Bandcamp` email:

![Screenshot 2024-05-26 at 0 01 09 AM](https://github.com/apparition47/MailTrackerBlockerApp/assets/3298414/2ee6f1f8-37d1-4034-a0d5-942989eeba20)

**Comment by plsvn** [comment]
yes, BandCamp, and others not working yesterday, are fine with 1.1.1 but... this one is not (second screen is with MTB disabled)

![Screenshot 2024-05-25 at 17 06 04](https://github.com/apparition47/MailTrackerBlockerApp/assets/73103621/7622e74a-77b1-4379-b1b1-be7d5bd295ff)

![Screenshot 2024-05-25 at 17 06 42](https://github.com/apparition47/MailTrackerBlockerApp/assets/73103621/d4f05de6-5b5e-4fc3-bb45-2678af5b6d47)

**Comment by plsvn** [comment]
oh... sorry: here it comes

[enjoy_ ricevuta del tuo noleggio.zip](https://github.com/apparition47/MailTrackerBlockerApp/files/15444022/enjoy_.ricevuta.del.tuo.noleggio.zip)

**Comment by apparition47** [comment]
Thanks for the sample. But it seems to be working for me on 1.1.1.

![SCR-20240526-bfpq](https://github.com/apparition47/MailTrackerBlockerApp/assets/3298414/3fa1aa9d-30e2-4939-ac48-c2ede6beb183)

I'll check a bit further

**Comment by plsvn** [comment]
![Screenshot 2024-05-25 at 17 28 46](https://github.com/apparition47/MailTrackerBlockerApp/assets/73103621/b888d5d6-eeb7-4887-acda-de460b1d3d81)

![Screenshot 2024-05-25 at 17 29 11](https://github.com/apparition47/MailTrackerBlockerApp/assets/73103621/4ebd0cd1-82f8-492e-ab7a-9faef579f50d)


:-|

**Comment by apparition47** [comment]
Is it just this one email now? I briefly mentioned this above but you may need to [delete your Envelope Index to fix it](https://c-command.com/spamsieve/help/how-can-i-rebuild-apple). I did this after updating to 1.1.1 from 1.1.0. If you're not comfortable doing that, let's see how future emails turn out.

**Comment by plsvn** [comment]
yes, so far looks to be just this one

Envelope Index rebuild already performed this morning

**Comment by plsvn** [comment]
ok: index rebuilt and not only that mail is still blank but also mails from a local forum that was fixed by 1.1.1 🤣 🙄

**Comment by apparition47** [comment]
Thanks for trying that. It doesn't seem to be related to the Envelope Index then.

In the meanwhile I'm releasing 1.1.2 tomorrow that includes a few more fixes that you can try out. I'll see if I can register for some newsletters from Audiophile Style as well.

**Comment by plsvn** [comment]
... and looks the issue is gone

thanks Aaron :-)

**Comment by apparition47** [comment]
Yay! Thanks for your patience
