### ISSUE TITLE
[Question] Do I have to keep the app open for it to work?

### ISSUE THREAD

**Issue by KeyboardChampion** [apparition47/MailTrackerBlockerApp#13]
I just have a question! Do I have to keep the app open for it to work? or can I just open the mail app by itself and it'll work?

**Comment by apparition47** [comment]
>Do I have to keep the app open for it to work?

Nope!

Once you've enabled the Extension ([see this screenshot](https://github.com/apparition47/MailTrackerBlockerApp/raw/main/Assets/mail_settings.png)), it will automatically block. You can click the `ⓧ` (just below the 2024/01/25) to see what it caught.

<img width="400" alt="Screenshot 2024-05-25 at 2 32 45 PM" src="https://github.com/apparition47/MailTrackerBlockerApp/assets/3298414/902d08a0-c7fc-4668-b55c-dab7f7caa716">

Thanks for the feedback. I'll have to update the page to make this more clear--trackers are 1x1 pixels big so it's not immediately obvious that the Extension is doing anything.

**Comment by apparition47** [comment]
Newer versions of MailTrackerBlocker (latest: 1.1.1) will now show an ⓧ. I recommend updating!
