### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by warmup72** [apparition47/MailTrackerBlockerApp#14]
It would be great if you could operate MTB with keyboard shortcuts. At least calling up the information would be missing here. The MTB window can then be closed with CMD-W.

**Comment by warmup72** [comment]
I think that's good. Maybe you can set a switch in the settings to decide whether you want the "X" or the detailed info in the mail. Then there would be something for everyone :-)
I'm primarily interested in whether there was a tractor in the mail or not. Details would be of secondary importance to me - they are enough in the app.

**Comment by apparition47** [comment]
Thanks for the feedback, I'll look into that.

Also just so you're aware and because it's not obvious, right now, if you tap on the ⓧ, a popup with all the detailed tracking info will appear.

**Comment by warmup72** [comment]
Hey Aaron,
thank you for this quick workaround. For me this helps!

Regards

Simon
