### ISSUE TITLE
extension crashes

### ISSUE THREAD

**Issue by malwcal** [apparition47/MailTrackerBlockerApp#19]
**Describe the bug**
From time to time I get told that mailtrackerblocker has 

**To Reproduce**
1.  Leave mail running
2.  Wait for crash

**Expected behavior**
No crash!

**Logs**

Crash logs via email to @apparition47 

**Environment (please complete the following information):**
 - OS: macOS 14.5
 - MailTrackerBlocker version: 1.1.3(44)

**Additional context**

**Comment by malwcal** [comment]
I should have mentioned this has happened 4 or 5 times since the last upgrade

**Comment by apparition47** [comment]
Give me some time to look into this.

In the meanwhile, deleting your 30-day MailTrackerBlocker history will fix this issue:

```bash
rm ~/Library/Group\ Containers/CW298N32P4.group.com.onefatgiraffe.mailtrackerblocker/Reports.sqlite*
```

**Comment by apparition47** [comment]
@malwcal Did you have the main app open ([with the tracker report which looks like this](https://github.com/apparition47/MailTrackerBlockerApp/assets/3298414/c013e7b8-e425-441f-be63-299f0553e743)) while using Mail? Just to double check, it was the mail extension that crashed and not the main app?

**Comment by malwcal** [comment]
Yes, I had the main app open.
My recollection is the first time it crashed the extension stopped working until I restarted mail.  Since then there have been a few crashes but it just seemed to be the main app,

**Comment by apparition47** [comment]
Releasing 1.1.5 tomorrow. Issue should be fixed there. Thanks for bringing this to my attention; didn't realize others were experiencing this as well.

**Comment by apparition47** [comment]
>My recollection is the first time it crashed the extension stopped working until I restarted mail.

This issue with extension not working (i.e. no ⓧ icon in the message header) I suspect is a different issue, possibly a Mail bug, which I detailed in #9

**Comment by apparition47** [comment]
Released. Let me know if there's any more main app/Tracker Report window crashes
