### ISSUE TITLE
Is beta testing period completed?

### ISSUE THREAD

**Issue by jmac-atgit** [apparition47/MailTrackerBlockerApp#22]
After having used the original MTB for many moons and reporting missed trackers, I installed the new MailTrackerBlocker app beta via enrollment in TestFlight.

I am currently running MTB Version 1.0.10 (34). In mid-May, I reported Issue #10 (now closed).

Noting that the beta is due to expire in 2 days, I returned here and also checked the App Store and now see the MTB App is at v. 1.1.6.

Is beta testing over? If not, is a new beta version available? If beta testing is over, I'm a bit surprised that the README still refers to beta testing via TestFlight.

Please post updated status information.

Thanks!

**Comment by apparition47** [comment]
Send me an email (you can see it from my profile @apparition47). I'll send you the app

**Comment by apparition47** [comment]
I've reached out to as many previous MTB contributors as I could to offer a free upgrade to the new version. Apologies if I missed you.
