### ISSUE TITLE
MailTrackerBlockerApp slows down Mail, macOS Sonoma

### ISSUE THREAD

**Issue by howdytom** [apparition47/MailTrackerBlockerApp#23]
Hi there,

I am using the latest MailTrackerBlockerApp 1.1.6 and I really like it. However, recently I have noticed a significant speed decrease. MailTrackerBlockerApp slows down Apple Mail dramatically. When I go through my mailbox, every message takes 2-4 seconds to load. It’s happening on tiny plaintext messages as well as with 1MB emails. Sometimes it takes 5 seconds until the message content shows up. It is terrible slow on a fast M2 Mac Studio! As soon as I disable the extension, Emails are loaded instantly.

Any plans for performance improvements?

**Comment by apparition47** [comment]
Hi again, thanks for your support first off.

This is a known issue with how Mail interacts some extensions. I've reported this to Apple. I encourage you to do so too via https://feedbackassistant.apple.com just to get their attention. But the good news is they have a "potential fix identified - for a future OS update". No clue which version of macOS they'll bring this fix to yet.

See #2 for more details.
