### ISSUE TITLE
Every second time I open some emails it is corrupt.

### ISSUE THREAD

**Issue by malwcal** [apparition47/MailTrackerBlockerApp#24]
**Describe the bug**
I go to open and email and it just displays blocks of seemingly random characters.  If I switch to another email and then back it will display.  From there every second one gives the corrupt view.

This has happened on multiple emails.

If I disable the extension I don't see this behaviour.

**Environment (please complete the following information):**
 - OS: MacOS 15.0
 - MailTrackerBlocker version: 1.1.7

**Additional context**
![corrupt](https://github.com/user-attachments/assets/77004032-3a26-4114-81b2-be2f1e6a33b5)

**Comment by apparition47** [comment]
Could you please try version 1.1.8 (see #21)?

**Comment by malwcal** [comment]
Upgraded to 1.1.8 but I am still seeing this bug on some emails -- reloading multiple times, sometimes the mail displays, sometimes not.

**Comment by apparition47** [comment]
Thanks. Found an email in my inbox that is behaving the same way. Doesn't happen on my Sonoma machine which is weird. Looking into it.

**Comment by apparition47** [comment]
Submitted another fix in 1.1.9
