### ISSUE TITLE
MTB 0.8.6 does not install on macOS 15.1

### ISSUE THREAD

**Issue by Thomas-U** [apparition47/MailTrackerBlockerApp#25]
MTB 0.8.6 does not install on macOS 18.1.

Version 0.8.0 seems to work still in Mail 16.0 (3826.200.121). 

<img width="617" alt="Screen-Shot 2024-10-29 at 14 18 56" src="https://github.com/user-attachments/assets/3a172be7-c102-48c1-8a49-d145464343b5">
--- 
macOS 15.1 (24B83) · MacBookPro M2 14” 64 GB RAM

**Comment by apparition47** [comment]
Your screenshot is showing the legacy mail plugin which is on a different repo: https://github.com/apparition47/MailTrackerBlocker. The bad news is that [Apple has decided to drop plug-ins support for Mail starting with Sonoma](https://www.macrumors.com/2023/06/14/macos-sonoma-drops-legacy-mail-app-plug-ins/) so plugins no longer work.

If you're running Sequoia, please checkout the app here: https://apps.apple.com/us/app/mailtrackerblocker/id6450760473
