### ISSUE TITLE
Corrupted text in mail messages (apostrophes are changed to "â€™"…)

### ISSUE THREAD

**Issue by apparition47** [apparition47/MailTrackerBlockerApp#5]
(Reported by @odysseus90210)

**Describe the bug**
When MTB is enabled, apostrophes and quotation marks are not displayed correctly in Mail messages: they appear as "â€™" and "â€œ", respectively. Accents don't appear correctly, either. 

**To Reproduce**
1. Load plugin. Display mail message.

**Expected behavior**
Text should not be modified by MTP

**Logs**
No logs

**Environment (please complete the following information):**
 - OS: Mac OS 14.3.1.
 - Other enabled plugins/extensions: Antidote

**Additional context**

**Comment by apparition47** [comment]
Not able to reproduce this issue. Is this happening in the title or the body of the email? If possible, please send me the affected `.eml` (email in my profile @apparition47)

**Comment by apparition47** [comment]
@odysseus90210 Not able to reproduce this issue. Is this happening in the title or the body of the email? If possible, please send me the affected `.eml` (email in my profile @apparition47)

**Comment by odysseus90210** [comment]
Body. I’ll try to reproduce and send you the email. —MarcOn Mar 7, 2024, at 1:16 AM, Aaron Lee ***@***.***> wrote:﻿
Not able to reproduce this issue. Is this happening in the title or the body of the email? If possible, please send me the affected .eml (email in my profile @apparition47)

**Comment by theorixx** [comment]
Hi,
I purchased your extension today and activated it immediately. Since I'm in Germany, my mails contain a lot of umlauts (äÄöÖüÜß). Mails filtered by MTB now look scrambled because the äöüß look like this: ä - Ã¤, Ä - Ã" ,ö - Ã¶ , Ö - Ã-, ü Ã¼, Ü - Ãœ, ß - ÃŸ. There must be something wrong with the utf-8 "conversion".
After a crash of Mail, your extension won't open even after a restart. If you are interested I can forward some of those mails.

**Comment by apparition47** [comment]
Yes, please send a sample email (File > Save As > Raw Message Source > [save the .eml])

email in my profile @apparition47

**Comment by theorixx** [comment]
Mmh, strange. MTB doesn't open anymore... I had to delete it and reinstall it from the app store

**Comment by apparition47** [comment]
@theorixx I think I have a fix for the encoding issue. Looks like the email was encoded in `windows-1252` when MTB assumes `UTF-8`. See 1.0.9 when it releases.

**Comment by blackketter** [comment]
Here's another email that MTB seems to display incorrectly (all random characters) when it's enabled:
[AppleSeed_ A new Safari build for macOS Ventura and Monterey is now available.eml.zip](https://github.com/apparition47/MailTrackerBlockerApp/files/15119212/AppleSeed_.A.new.Safari.build.for.macOS.Ventura.and.Monterey.is.now.available.eml.zip)

**Comment by apparition47** [comment]
@blackketter That's on version 1.0.9? Will have a look after I return

**Comment by blackketter** [comment]
Ah, no, that's on the TestFlight version 9999.  My bad, should I open a separate issue?

**Comment by luteco-flu** [comment]
Same problem with Umlaut characters as well as bullets, etc. However, as soon as I opened the app (Version 1.0.8 (32)) the problem was not there anymore...

**Comment by apparition47** [comment]
If you're having issues, please email me a eml of the problematic email plus the version number of MTB.

**Comment by odysseus90210** [comment]
This is constantly a problem with your plugin. I’ve sent you a problematic email.

—Marc

**Comment by apparition47** [comment]
@odysseus90210 @blackketter Thanks for the samples. Should be fixed in 1.0.10 (available soon)

@luteco-flu Please try 1.0.10. If you still see an issue, please provide a `.eml` for me to look at.

**Comment by apparition47** [comment]
>Mmh, strange. MTB doesn't open anymore... I had to delete it and reinstall it from the app store

@theorixx This is about the 🧩 puzzle icon not appearing sometimes right? I've opened a separate issue #9 about this. If possible, please [report to Apple](https://feedbackassistant.apple.com) referencing `FB13801609`.
