### ISSUE TITLE
Cannot preview PDFs

### ISSUE THREAD

**Issue by malwcal** [apparition47/MailTrackerBlockerApp#6]
**Describe the bug**
When the extension is enabled I cannot preview PDFs.   

(To view them I need to download and then view)

In fact: the plugin strips the ".pdf" off the end of the filename.

**To Reproduce**
1. Open an email with a pdf
2. Select it and press space
3. See no preview
4. Click the paper clip and notice that there is no .pdf at the end of the filename

If I disable the extension then go back to the same message it will work as normal.
If I then enable the extension and go back to the same message it is broken again.

**Expected behavior**
Previews should work and filenames not be changed.

**Logs**

**Environment (please complete the following information):**
 - OS: 14.4 (23E214)
 - Other enabled plugins/extensions: None

**Additional context**

**Comment by apparition47** [comment]
Interesting. This seems to happen in some emails and not others. Will look into it, thanks

**Comment by apparition47** [comment]
Fixed for 1.0.7.

**Comment by apparition47** [comment]
Go ahead and update then let me know if you still have issues

**Comment by malwcal** [comment]
This seems to be fixed!  Thanks!
