### ISSUE TITLE
Block Rule.io tracker 

### ISSUE THREAD

**Issue by noamvokaal** [apparition47/MailTrackerBlockerApp#7]
The app does not block trackers from Rule.io. I found this block of code inside an email:

`<div style=3D"display:none; whit=
e-space:nowrap; font:15px courier; line-height:0;">=C2=A0</div><img src=3D'=
https://app.rule.io/track/image/a/n_3sdd/d/n_5in617/di/n_ru/s/n_4t5nfo/e/n_m=
4kjr' width=3D'1' height=3D'1' alt=3D'' /><div style=3D'display:none !impor=
tant;mso-hide:all;'><a href=3D'https://app.rule.io/lookup' style=3D'display=
: none;'><i class=3D'btlink'></i></a></div>`

If you want to take a look at the .eml file, please provide me an email address, and I’ll send the file to you :-)

Thanks for a fantastic app!

**Comment by apparition47** [comment]
Thanks for your submission. Updated the app (1.0.8) and the older plugin (0.8.4)
